export const SEND_CODE = 'SEND_CODE'
export const CONFIRM_CODE = 'CONFIRM_CODE'
export const RECEIVE_CODE = 'RECEIVE_CODE'
export const REQUEST_CODE = 'REQUEST_CODE'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
