export const REQUEST_FILTERS = 'REQUEST_FILTERS';
export const REQUEST_FILTERS_SUCCESS = 'REQUEST_FILTERS_SUCCESS';
export const ADD_EMAIL_TO_NEW_FILTER = 'ADD_EMAIL_TO_NEW_FILTER';
export const FINISH_EMAIL_SELECTION = 'FINISH_EMAIL_SELECTION';
export const POST_NEW_RECIPE = 'POST_NEW_RECIPE';
export const START_NEW_RECIPE = 'START_NEW_RECIPE';
export const NEW_RECIPE_SUCCESS = 'NEW_RECIPE_SUCCESS';
export const INCREMENT_FLOW = 'INCREMENT_FLOW';
